# Generated by Django 3.2.24 on 2024-03-04 14:28

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('start', models.CharField(max_length=15)),
                ('end', models.CharField(max_length=15)),
                ('description', models.TextField(default='No description is provided!')),
            ],
        ),
        migrations.CreateModel(
            name='TourAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='Warning editing thisfield will change the About Us section on the home page!')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('duration', models.CharField(default='3 days', max_length=50)),
                ('start_place', models.CharField(max_length=50)),
                ('end_place', models.CharField(max_length=50)),
                ('group_size', models.IntegerField(choices=[(2, 'small'), (4, 'medium'), (8, 'Large')], default=2)),
                ('description', models.TextField(default='No description is provided!')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='Bamyan.season')),
            ],
        ),
    ]
