# Generated by Django 3.2.24 on 2024-03-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bamyan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='group_size',
            new_name='package_size',
        ),
    ]
